# -*- coding: utf-8 -*-
"""classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LDsrJkSWOz0aPCPEauq2u4zVbbEiAXTx
"""

!pip install transformers

from transformers import  pipeline

classifier =pipeline("text-classification",model="distilbert/distilbert-base-uncased-finetuned-sst-2-english")

classifier("i absolutely love this new phone! the phone camera quality ids good")

classifier("this movie is very boring , i almost fell a sleep")

!pip install gradio

import gradio as gr
from transformers import pipeline
classifier =pipeline("text-classification",model="distilbert/distilbert-base-uncased-finetuned-sst-2-english")
def predict_sentiment(text):
  return classifier(text)[0]

#gr.Interface(fn=predict_sentiment,inputs="text",outputs="text").launch()
gr.Interface(fn=predict_sentiment,
             inputs=[gr.Textbox(label="Insert prompt here",lines=5),
                     ],outputs=[gr.Textbox(label="Output here",lines=5)],title="Amarjeet App").launch()

# Use a pipeline as a high-level helper
from transformers import pipeline

messages = [
    {"role": "user", "content": "Who are you?"},
]
pipe = pipeline("text-generation", model="deepseek-ai/DeepSeek-Prover-V2-7B", trust_remote_code=True)
pipe(messages)